# 4. 예외

자바 개발자가 가장 신경 쓰기 귀찮아하는 것 중의 하나가 바로 예외처리다. 정상적인 결과와 흐름을 보여주는 코드를 만들기도 버거운데 예외상황까지 처리해야 한다는 사실이 부담스러울 수도 있다. 그래서 예외와 관련된 코드는 자주 엉망이 되거나 무성의하게 만들어지기 쉽다. 때론 잘못된 예외처리 코드 때문에 찾기 힘든 버그를 낳을 수도 있고, 생각지 않았던 예외상황이 발생했을 때 상상 이상으로 난처해질 수도 있다.


## 4.1 사라진 SQLException

3장에서 JdbcContext 로 만들었던 코드를 스프링의 JdbcTemplate 을 적용하도록 바꾸면서 설명하지 않고 넘어간 부분이 있다. JdbcTemplate 으로 바꾸기 전과 후의 deleteAll() 메서드를 비교해보고 무엇이 달라졌는지 찾아보자.

JdbcTemplate 적용 전
```java
public void deleteAll() throws SQLException {
   this.jdbcContext.executeSql("delete from users"); 
}
```

JdbcTemplate 적용 후
```java
public void deleteAll() throws SQLException {
   this.jdbcTemplate.update("delete from users"); 
}
```

### 4.1.1 초난감 예외처리

#### 예외 블랙홀

아래 코드는 기본적인 JDBC 코드이다.

```java
try{
    // ...
}
catch(SQLException e) {

}
```

JDBC API를 사용하면 IDE가 친절하게 빨간  줄을 그어주며 '처리되지 않은 예외가 있다'고 에러 표시를 해준다. 이를 보고 자바 언어 기초 시간에 배운 대로 try/catch 블록을 둘러싸주는 것으로 해결한다. 컴파일러 에러 메시지도 없어지고 간단한 예제에서라면 별문제 없이 잘 동작한다.

예외가 발생하면 그것을 catch 블록을 써서 잡아내는 것까지는 좋은데 그리고 아무것도 하지 않고 별문제 없는 것처럼 넘어가 버리는 건 정말 위험한 일이다. 원치 않은 예외가 발생하는 것보다도 훨씬 더 나쁜 일이다. 왜냐하면 프로그램 실행 중에 어디선가 오류가 있어서 예외가 발생했는데 그것을 무시하고 계속 진행해버리기 때문이다. 결국 발생한 예외로 인해 어떤 기능이 비정상적으로 동자하거나, 메모리나 리소스가 소진되거나, 예상치 못한 다른 문제를 일으킬 것이다. 최종적으로 오작동을 하거나 시스템 오류가 나서 운영자가 알아차렸을 때는 이미 조치를 취하기엔 너무 늦었다.

아래 코드도 마찬가지다.

```java
} catch (SQLException e) {
    System.out.println(e);    
}
```

```java
} catch (SQLException e) {
    e.printStackTrace();    
}
```
예외가 발생하면 화면에 출력해주는데 뭐가 문제일까? 개발 중에는 IDE 콘솔이나 서버 실행창에 이 메시지가 눈에 확 띄게 보이니 문제가 생겨도 금방 알아차리고 뭔가 조취를 취할 수 있을지 모르겠다. 그래 봤자 다른 로그나 메시지에 금방 묻혀버리면 놓치기 쉽상이다. 운영서버에 올라가면 더욱 심각하다. 콘솔 로그를 누군가가 계속 모니터링 하지 않는 한 이 예외 코드는 심각한 폭탄으로 남아있을 것이다. **예외는 처리돼야 한다.** 그런데 위의 코드들은 catch 블록을 이용해 화면에 메시지를 출력한 것은 예외를 처리한 게 아니다.

예외를 처리할 때 반드시 지켜야 할 핵심 원칙은 한 가지다. **모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보돼야 한다.** 

SQLException이 발생하는 이유는 SQL에 문법 에러가 있거나 DB에서 처리할 수 없을 정도로 데이터 액세스 로직에 심각한 버그가 있거나, 서버가 죽거나 네트워크가 끊기는 등의 심각한 상황이 벌어졌기 때문이다. 그런데 그냥 예외를 무시하고 정상적으로 동작하는 있는 것처럼 모른 척 다음 코드로 실행을 이어간다는 건 말이 되지 않는다. 콘솔이나 로그에 예외 메시지를 출력하는 건 아무런 도움이 되지 않다. 아래와 같이 만드는게 백 배 낫다.

```java
} catch (SQLException e) {
    e.printStackTrace();
    System.exit(1);
}
```
물론 실전에서 이렇게 만들라는 건 아니다. 예외를 무시하거나 잡아먹어 버리는 코드는 만들지 말라는 뜻이다.

#### 무의미하고 무책임한 throws

catch 블록으로 예외를 잡아봐야 해결할 방법도 없고 JDK API나 라이브러리가 던지는 각종 이름도 긴 예외들을 처리하는 코드를 매번 throws로 처리하기 귀찮아지기 시작하면, 아래와 같이 메서드 선언에 throws Exception 을 기계적으로 붙이는 개발자도 있다.

<img width="446" alt="image" src="https://github.com/pak0426/pak0426/assets/59166263/da03b2e0-8c90-4e24-8302-5f3c8da4464e">

예외를 흔적도 없이 먹어치우는 예외 블랙홀보다는 조금 낫긴 하지만 이런 무책임한 throws 선언도 심각한 문제점이 있다.

자신이 사용하려고 하는 메서드에 throws Exception이 선언되어 있다고 생각해보자. 그런 메서드 선언에서는 의미 있는 정보를 얻을 수 없다. 정말 무엇인가 실행 중에 예외적인 상황이 발생할 수 있다는 것인지, 아니면 그냥 습관적으로 복사해서 붙여놓은 것이지 알 수가 없다. 결국 이런 메서드를 사용하는 메서드에서도 역시 throws Exception을 따라서 붙이는 수 밖에 없다. 결과적으로 적절한 처리를 통해 복구될 수 있는 예외상황도 제대로 다룰 수 있는 기회를 박탈당한다.

### 4.1.2 예외의 종류와 특징

그렇다면 예외를 어떻게 다뤄야할 까? 예외처리에 관해서는 자바 개발자들 사이에서도 오랫동안 많은 논쟁이 있었다. 가장 큰 이슈는 **체크 예외** 라고 불리는 명시적인 처리가 필요한 예외를 사용하고 다루는 방법이다. 자바에서 throw 를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있다.

### Error

첫째는 java.lang.Error 클래스의 서브클래스들이다. 에러는 시스템에 뭔가 비정상적인 상황이 발생했을 경우에 사용된다. 그래서 주로 자바 VM에서 발생시키는 것이고 애프리케이션 코드에 잡으려고 하면 안 된다. OutOfMemoryError나 ThreadDeath 같은 에러는 catch 블록으로 잡아봤자 아무런 대응 방법이 없기 때문이다. 

따라서 시스템 레벨에서 특별한 작업버을 하는 게 아니라면 애플리케이션에는 이런 에러에 대한 처리는 신경 쓰지 않아도 된다.

#### Exception과 체크 예외

java.lang.Exception 클래스와 그 서브클래스로 정의되는 예외들은 에러와 달리 개발자들이 만든 애플리케이션 코드의 작업 중에 예외상황이 발생했을 경우에 사용된다.

Exception 클래스는 다시 **체크 예외**와 **언체크 예외**로 구분된다. 

체크 예외는 Exception 클래스의 서브 클래이스이면서 RuntimException 클래스를 상속하지 않은 것들이고, 언체크 예외는 RuntimeException을 상속한 클래스들을 말한다.

RuntimeException은 Exception의 서브클래스이므로 Exception의 일종이긴 하지만 자바는 이 RuntimeException과 그 버스클래스는 특별하게 다룬다. 아래 그림은 Exception 클래스의 서브클래스를 체크 예외와 언체크 예외로 구분한 것이다.

<img width="537" alt="image" src="https://github.com/pak0426/pak0426/assets/59166263/f56f6069-2bf1-4cd4-b7aa-8c24602a05b8">

일반적으로 예외라고 하면 Exception 클래스의 서브클래스 중에서 RuntimeException을 상속하지 않은 것만을 말하는 체크 예외라고 생각해도 된다. 체크 예외가 발생할 수 있는 메서드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야 한다. 사용할 메서드가 체크 예외를 던진다면 이를 catch 문으로 잡든지, 아니면 다시 throws를 정의해서 메서드 밖으로 던져야 한다. 그렇지 않으면 컴파일 에러가 발생한다.

자바 언어와 JDK의 초기 설계자들은 체크 예외를 발생 가능한 예외에 모두 적용하려고 했던 것 같다. 그래서 IOException 이나 SQLException을 비롯해서 예외적인 상황에서 던져질 가능성이 있는 것들 대부분이 체크 예외로 만들어져 있다.

#### RuntimeException과 언체크/런타임 예외

java.lang.RuntimeException 클래스를 상속한 예외들은 명시적인 예외처리를 강제하기 않기 때문에 언체크 예외라고 불린다. 또는 대표 클래스 이름을 따서 런타임 예외라고도 한다. 에러와 마찬가지로 이 런타임 예외는 catch 문으로 잡거나 throws로 선언하지 않아도 된다. 물론 명시적으로 잡거나 throws 로 선언해줘도 상관 없다.

런타임 예외는 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들이다. 대표적으로 오브젝트를 할당하지 않은 레퍼런스 변수를 사용하려고 시도했을 때 발생하는 NullPointException 이나, 허용되지 않는 값을 사용해서 메서드를 호출할 때 발생하는 IllegalArgumentException 등이 있다. 이런 예외는 코드에서 미리 조건을 체크하도록 주의 깊게 만든다면 피할 수 있다. 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 만든 것이 런타임 예외다. 따라서 런타임 예외는 예상하지 못했던 예외상황에서 발생하는 게 아니기 때문에 굳이 catch 나 throws 를 사용하지 않도록 되도록 만든 것이다.

그런데 자바 언어를 설계하고 JDK를 개발한 사람들의 이런 설계의도는 현실과 잘 맞지 않았고 비난의 대상이 되기도 했다. 특히 체크 예외의 불필요성을 주장하는 사람들이 늘어갔다. 체크 예외가 예외처리를 강제하는 것 때문에 예외 블랙홀이나 무책임한 throws 같은 코드가 남발됐다. 최근에 새로 등장하는 자바 표준 스펙의 API들은 예상 가능한 예외상황을 다루는 예외를 체크 예외로 만들지 않는 경향이 있기도 하다.

### 4.1.3 예외처리 방법

효과적인 예외처리 전략을 생각해보자.

#### 예외 복구

첫 번째 예외처리 방법은 예외상황을 파악하고 문제를 해결해서 저앙 상태로 돌려놓는 것이다.

예를 들어 사용자가 요청한 파일을 읽으려고 시도했는데 해당 파일이 없거나 다른 문제가 있어서 읽히지 않아서 IOException이 발생햇다고 생각해보자. 이때는 사용자에게 상황을 알려주고 다른 파일을 이용하도록 안내해서 예외상황을 해결할 수 있다. **예외로 인해 기본 작업 흐름이 불가능하면 다른 작업 흐름으로 자연스럽게 유도해주는 것이다. 이런 경우 예외상황은 다시 정상으로 돌아오고 예외를 복구했다고 볼 수 있다.** 단, **IOException 에러 메시지가 사용자에게 그냥 던저니는 것은 예외 복구라고 볼 수 없다.** 예외가 처리됐으면 비록 기능적으로는 사용자에게 예외상황으로 비쳐도 애플리케이션에서는 정상적으로 설계된 흐름을 따라 진행돼야 한다.

네트워크가 불안해서 가끔 서버에 접속이 잘 안되는 환경에 있는 시스템이라면 원격 DB 서버에 접속하다 실패해서 SQLException이 발생하는 경우에 재시도를 해볼 수 있다. 네트워크 접속이 원활하지 않아서 예외가 발생했다면 일정 시간 대기했다가 다시 접속을 시도해보는 방법을 사용해서 예외상황으로부터 복구를 시도할 수 있다. 물론 정해진 횟수만큼 재시도해서 실패했다면 예외 복구는 포기해야 한다.

예외처리 코드를 강제하는 체크 예외들을 이렇게 예외를 어떤 식으로든 복구할 가능성이 있는 경우에 사용한다. API를 사용하는 개발자로 하여금 예외상황이 발생할 수 있음을 인식하도록 도와주고 이에 대한 적절한 처리를 시도해보도록 요구하는 것이다.

아래 코드는 통제 불가능한 외부 요인으로 인해 예외가 발생하면 MAX_RETRY 만큼 재시도를 하는 간단한 예다. 사전에 미리 성공 여부를 확인할 수 없고, 재시도가 의미 있는 경우라면 이렇게 최대 횟수만큼 반복적으로 시도함으로써 예외상황에서 복구할 수 있다.

```java
int maxretry = MAX_RETRY;
while (maxretry --> 0) {
    try {
        ...         // 예외가 발생할 가능성이 있는 시도
        return;     // 작업 성공
    }
    catch (SomeException e) {
        // 로그 출력. 정해진 시간만큼 대기
    }
    finally {
        // 리소스 반납. 정리 작업
    }
} 
throw new RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외 발생
```

#### 예외처리 회피

두 번째 방법은 예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버리는 것이다. throws 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch 문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는 것이다.

예외를 자신이 처리하지 않고 회피하는 방법이다. 빈 catch 블록으로 잡아서 예외가 발생하지 않은 것처럼 만드는 경우는, 드물지만 특별한 의도를 가지고 예외를 복구했거나 아무 개념이 없어서 그런 것이지  회피한 것은 아니다. 예외처리를 회피하려면 반드시 다른 오브젝트나 메서드가 예외를 대신 처리할 수 있도록 아래 2가지 방법처럼 던져줘야 한다.

```java
public void add() throws SQLException {
    // JDBC API    
}
```

```java
import java.sql.SQLException;

public void add() throws SQLException {
    try {
        // JDBC API
    } catch (SQLException e) {
        // 로그 출력
        throw e;
    }
}
```

JdbcContext나 JdbcTemplate이 사용하는 콜백 오브젝트는 메서드 선언을 보면 알겠지만 ResultSet 이나 PreparedStatement 등을 이용해서 작업하다 발생하는 SQLException을 자신이 처리하지 않고 템플릿으로 던져버린다. 콜백 오브젝트의 메서드는 모두 throws SQLException이 붙어 있다. SQLException을 처리하는 일은 콜백 오브젝트의 역할이 아니라고 보기 때문이다. 콜백 오브젝트의 메서드는 SQLException에 대한 예외를 회피하고 템플릿 레벨에서 처리하도록 던져준다.

하지만 콜백 템플릿처럼 긴밀하게 역할을 분담하고 있는 관계가 아니라면 자신의 코드에서 발생하는 예외를 그냥 던져버리는 건 무책임한 책임회피일 수 있다. 만약 DAO가 SQLException을 생각 없이 던져버리면 어떻게 될까? DAO를 사용하는 서비스 계층이나 웹 컨트롤러에서 과연 SQLException을 제대로 처리할 수 있을까? 아마도 이런 경우라면 DAO에서 던진 SQLException을 서비스 계층 메서드가 다시 던지고, 컨트롤러도 다시 던지도록 선언해서 예외는 그냥 서버로 전달되고 말 것이다. 아마도 throws SQLException과 같이 구체적인 예외를 던지도록 선언하기가 귀찮아서 모든 예외를 생각 없이 던져버리게 하는 throws Exception을 사용할 가능성이 높다.

**예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다.** 콜백/템플릿처럼 긴밀한 관계에 있는 다른 오브젝트에게 예외처리 책임을 분명하게 지게 하거나, 자신을 사용하는 쪽에서 예외를 다루는 게 최선의 방법이라는 분명한 확신이 있어야 한다.

#### 예외 전환

마지막으로 예외를 처리하는 방법은 **예외 전환**을 하는 것이다. 예외 회피와 비슷하게 예외를 복구해서 정상적인 상태로는 만들 수 없기 때문에 예외를 메서드 밖으로 던지는 것이다. **하지만 예외 회피와 달리, 발생한 예외를 그대로 넘기는 게 아니라 적절한 예외로 전환해서 던진다는 특징이 있다.**

예외 전환은 보통 두 가지 목적으로 사용된다.

첫째는 **내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우에, 의미를 분명하게 해줄 수 있는 예외로 바꿔주기 위해서다.** API가 발생하는 기술적인 로우레벨을 상황에 적합한 의미를 가진 예외로 변경하는 것이다. 

예를 들어 새로운 사용자들 등록하려고 시도했을 때 아이디가 같은 사용자가 있어서 DB 에러가 발생하면 JDBC API는 SQLException을 발생시킨다. 이 경우 DAO 메서드가 SQLException을 그대로 밖으로 던져버리면, DAO를 이용해 사용자를 추가하려고 한 서비스 계층 등에서는 왜 SQLException이 발생했는지 쉽게 알 방법이 없다. 로그인 아이디 중복 같은 경우는 충분히 예상 가능하고 복구 가능한 예외 상황이다. 이럴 땐 DAO에서 SQLException의 정보를 해석해서 DuplicatedUserIdException 같은 예외로 바꿔서 던져주는 게 좋다. 의미가 분명한 예외가 던져지면 서비스 계층 오브젝트에는 적절한 복구 작업을 시도할 수 있다. 서비스 계층 오브젝트에서 SQLException의 원인을 해석해서 대응하는 것도 불가능하지는 않지만, 특정 기술의 정보를 해석하는 코드를 비즈니스 로직을 담은 서비스 계층에 두는 건 매우 어색하다. 따라서 DAO 메서드에서 기술에 독립적이며 의미가 분명한 예외로 전환해서 던져줄 필요가 있다.

아래 코드는 중복된 아이디 값 때문에 에러가 나는 경우를 좀 더 의미 있는 DuplicateKeyException으로 전환해주는 DAO 메서드의 예시다.

```java
public void add(User user) throws DuplicatedUserIdException, SQLException {
    try {
    
    }
    catch(SQLException e) {
        if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
            throw DuplicatedUserIdException();
        else
            throw e;
    }
}
```

보통 전환하는 예외에 원래 발생한 예외를 담아서 **중첩 예외**로 만드는 것이 좋다. 중첩 예외는 getCause() 메서드를 이용해서 처음 발생한 예외가 무엇인지 확인 할 수 있다. 중첩 예외는 아래 코드 2개 처럼 새로운 예외를 만들면서 생성자나 initCause() 메서드로 근본 원인이 되는 예외를 넣어주면 된다.

중첩 예외1
```java
catch(SQLException e) {
   ...
   throw DuplicatedUserIdException(e);         
}
```

중첩 예외2
```java
catch(SQLException e) {
   ...
   throw DuplicatedUserIdException().initCause(e);         
}
```

두 번째 전환 방법은 예외를 처리하기 쉽고 단순하게 만들기 위해 포장하는 것이다. 중첩 예외를 이용해 새로운 예외를 만들고 원인이 되는 예외를 내부에 담아서 던지는 방식은 같다. 하지만 의미를 명확하게 하려고 다른 예외로 전환하는 것이 아니다. 주로 예외처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우에 사용한다.

대표적으로 EJBException을 들 수 있다. EJB 컴포넌트 코드에서 발생하는 대부분의 체크 예외는 비즈니스 로직으로 볼 때 의미 있는 예외이거나 복구 가능한 예외가 아니다. 이런 경우에는 런타임 예외인 EJBException으로 포장해서 던지는 편이 낫다.

<img width="577" alt="image" src="https://github.com/pak0426/pak0426/assets/59166263/77d5ca36-d97f-449c-a8c1-3964d868c3e0">

EJBException은 RuntimeException 클래스를 상속한 런타임 예외다. 이렇게 런타임 예외로 만들어서 전달하면 EJB는 이를 시스템 익셉션으로 인식하고 트랜잭션을 자동으로 롤백해준다. 런타임 예외이기 때문에 EJB 컴포넌트를 사용하는 다른 EJB나 클라이언트에서 일일이 예외를 잡거나 다시 던지는 작업을 할 필요가 없다. 이런 예외는 잡아도 복구할 만한 방법이 없기 때문이다.

반대로 애플리케이션 로직상에서 예외조건이 발견되거나 예외상황이 발생할수도 있다. 이런 것은 API가 던지는 예외가 아니라 애플리케이션 코드에서 의도적으로 던지는 예외다. 이때는 체크 예외를 사용하는 것이 적절하다. **비즈니스적인 의미가 있는 예외는 이에 대한 적절한 대응이나 복구 작업이 필요하기 때문이다.**

일반적으로 체크 예외를 계속 throws를 사용해 넘기는건 무의미하다. 메서드 선언은 지저분해지고 장점이 없다. 어차피 복구 불가능한 예외라면 가능한 한 빨리 런타임 예외로 포장해 던지게 해서 다른 계층의 메서드를 작성할 때 불필요한 throws 선언이 들어가지 않도록 해줘야 한다.

### 4.1.4 예외처리 전략

사실 자바의 예외를 이용하는 것은 간단하다. 하지만 예외를 효과적으로 사용하고, 예외가 발생하는 코드를 깔끔하게 정리하는 데는 여러 가지 신경 써야 할 사항이 많다. 지금까지 살펴본 예외의 종류와 처리 방법 등을 기준으로 일관된 예외처리 전략을 정리해보자. 


#### 런타임 예외의 보편화

일반적으로 체크 예외가 일반적인 예외를 다루고, 언체크 예외는 시스템 장애나 프로그램상의 오류에 사용한다고 했다. 문제는 체크 예외는 복구할 가능성이 조금이라도 있는, 말 그대로 예외적인 상황이기 때문에 자바는 이를 처리하는 catch 블록이나 throws 선언을 강제하고 있다는 점이다.

자바 엔터프라이즈 서버환경은 수많은 사용자가 동시에 요청을 보내고 각 요청이 독립적인 작업으로 취급된다. 하나의 요청을 처리하는 중에 예외가 발생하면 해당 작업만 중단시키면 그만이다. 독립형 애플리케이션과 달리 서버의 특정 계층에서 예외가 발생했을 때 작업을 일시 중지하고 사용자와 바로 커뮤니케이션하면서 예외상황을 복구할 수 있는 방법이 없다.

차라리 애플리케이션 차원에서 예외상황을 미리 파악하고, 예외가 발생하지 않도록 차단하는 게 좋다. 또는 프로그램의 오류나 외부 환경으로 인해 예외가 발생하는 경우라면 빨리 해당 요청의 작업을 취소하고 서버 관리자나 개발자에게 통보해주는 편이 낫다.

#### add() 메서드의 예외처리

```java
public void add(User user) throws DuplicatedUserIdException, SQLException {
    ...
}
```

위 코드의 add() 메서드는 DuplicatedUserIdException, SQLException 두 가지 체크 예외를 던지게 되어 있다. JDBC 코드에서 SQLException이 발생할 수 있는데, 그 원인이 ID 중복이라면 좀 더 의미 있는 예외인 DuplicatedUserIdException 으로 전환해주고, 아니라면 SQLException 을 그대로 던지게 했다. DuplicatedUserIdException 은 충분히 복구 가능한 예외이므로 add() 메서드를 사용하는 쪽에서 잡아서 대응할 수 있다. 하지만 SQLException 은 대부분 복구 불가능한 예외이므로 잡아봤자 처리할 것도 없고, 결국 throws 를 타고 계속 앞으로 전달되다가 애플리케이션 밖으로 던져질 것이다. 그럴 바에는 그냥 런타임 예외로 포장해 던져버려서 그 밖의 메서드들이 신경 쓰지 않게 해주는 편이 낫다.

DuplicatedUserIdException 도 굳이 체크 예외로 둬야 하는 것은 아니다. DuplicatedUserIdException처럼 의미 있는 예외는 add() 메서드를 바로 호출한 오브젝트 대신 더 앞단의 오브젝트에서 다룰 수 있다. **어디에서든 DuplicatedUserIdException 을 잡아서 처리할 수 있다면 굳이 체크 예외로 만들지 않고 런타임 예외로 만드는 게 낫다. 대신 add() 메서드를 사용하는 코드를 개발자에게 의미 있는 정보를 전달해줄 수 있다.**

이 방법을 이용해 add() 메서드를 수정해보자.

```java
class DuplicatedUserIdException extends RuntimeException {
    public DuplicatedUserIdException(Throwable cause) {
        super(cause);
    }
}
```

이제 add() 메서드를 수정하자. 기존 코드는 SQLException 을 직접 메서드 밖으로 던지게 했는데, 이제는 런타임 예외로 전환해서 던지도록 만든다. 기존의 아이디 중복 때문에 SQLException이 발생한 경우에는 DuplicatedUserIdException을 던지게 하는 코드는 그대로 두면 된다.

```java
public void add(User user) throws DuplicatedUserIdException {
    try {
    
    }
    catch(SQLException e) {
        if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
            throw new DuplicatedUserIdException(); // 예외 전환
        else
            throw new RuntimeException(); // 예외 포장
    }
}
```

이제 이 add() 메서드를 사용하는 오브젝트는 SQLException 을 처리하기 위해 불필요한 throws 선언을 할 필요는 없으면서 필요한 경우 아이디 중복 상황을 처리하기 위해 DuplicatedUserIdException 을 이용할 수 있다. DuplicatedUserIdException 이 발생한 경우라면 사용자가 요청한 아이디 대신 사용할 수 있는 추천 아이디를 만들어 아이디 중복 메시지와 함께 제공해주는 방법을 사용하면 좋을 것이다.

#### 애플리케이션 예외